server:
  port: 18081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zero-labs?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 127.0.0.1 # 地址
      port: 6379 # 端口
      database: 0 # 数据库索引

  jackson:
    serialization:
      write-dates-as-timestamps: false # 不要将日期写成时间戳

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto  # Id主键自增
      logic-delete-value: 1  # 逻辑已删除值
      logic-not-delete-value: 0  # 逻辑未删除值
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.zero.lab.oatuh2.mysql.dataobject

logging:
  level:
    # dao开启debug模式 mybatis输入sql
    com:
      mars:
        lab:
          zero:
            oauth2:
              mapper: debug

